### PR TITLE
created branch-x and created a test class also

### PR DESCRIPTION
**Pull request by robertbob93**
Hello Lead,
I am doing a pull request to review the committed code. Please review and approve.

Regards,
Robert Bob

### CODE REVIEW

**Comment by befiskaria** [comment]
Hi Robert, 
your code looks code, please change the string to automation.

Regards
QA Lead

**Comment by robertbob93** [comment]
Hi lead,
I have added additional checks. Please approve.

Regards,
Robert

**Comment by befiskaria** [comment]
Hey Robert,
Your code looks good and it is approved

**Comment by befiskaria** [comment]
go ahead and merge to the master branch

regards,
lead

**Pull request merged**
